---
version: '3'

services:
  ansible:
    image: registry.gitlab.com/appointmentguru/ops/playbooks:master
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False
      - CI_PROJECT_NAME=${CI_PROJECT_NAME}
      - CI_REGISTRY_USER=${CI_REGISTRY_USER}
      - CI_REGISTRY_PASSWORD=${CI_REGISTRY_PASSWORD}
      - CI_REGISTRY_IMAGE=${CI_REGISTRY_IMAGE}
      - CI_REGISTRY=${CI_REGISTRY}
      - CI_COMMIT_REF_SLUG=${CI_COMMIT_REF_SLUG}

