# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-10 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(max_length=36)),
                ('cardholder_name', models.CharField(max_length=255)),
                ('registration_id', models.CharField(max_length=46)),
                ('bin', models.CharField(max_length=255)),
                ('expiry_month', models.PositiveIntegerField()),
                ('expiry_year', models.PositiveIntegerField()),
                ('last_four_digits', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, max_length=36, null=True)),
                ('name', models.CharField(blank=True, max_length=36, null=True)),
                ('company', models.CharField(blank=True, max_length=36, null=True)),
                ('mobile', models.CharField(blank=True, max_length=36, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=6)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrance_rate', models.CharField(choices=[('M', 'Monthly'), ('A', 'Annually')], default='M', max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('new', 'new'), ('processing', 'processing'), ('success', 'success'), ('failed', 'failed'), ('pending', 'pending')], default='new', max_length=10)),
                ('currency', models.CharField(default='ZAR', max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_recurring', models.BooleanField(default=True, help_text='If true, when transaction successfully completes, it will create another recurring payment 1 month from now')),
                ('run_on_creation', models.BooleanField(default=False, help_text="If this is selected, we'll try run this payment immediately")),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='copyandpay.CreditCard')),
                ('customer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='copyandpay.Customer')),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='copyandpay.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, max_length=128, null=True)),
                ('currency', models.CharField(max_length=6)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transaction_id', models.CharField(max_length=255)),
                ('ndc', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_brand', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_type', models.CharField(max_length=6)),
                ('registration_id', models.CharField(blank=True, max_length=42, null=True)),
                ('result_code', models.CharField(max_length=22)),
                ('result_description', models.TextField(blank=True, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_transaction', to='copyandpay.CreditCard')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_transaction', to='copyandpay.Customer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_transaction', to='copyandpay.Product')),
            ],
        ),
    ]
