# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-11 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copyandpay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.CharField(default='user', max_length=255),
        ),
    ]
