# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-11 09:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('order_type', models.CharField(default='type', max_length=100)),
                ('order_level', models.CharField(default='none', max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('isRecurring', models.BooleanField(default=False)),
                ('isSettled', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('image', models.CharField(default='default.jpg', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
