# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-11 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ownBox',
            field=models.ImageField(default='none', upload_to='lists'),
        ),
    ]
